cd ..

sudo git clone https://github.com/internousdevjava/201407-shotaro.nakagawa
sudo git clone https://github.com/internousdevjava/201407-satoshi.igarashi
sudo git clone https://github.com/internousdevjava/201407-toshihiro.takagi
sudo git clone https://github.com/internousdevjava/201407-tatsuhiko.sekine
sudo git clone https://github.com/internousdevjava/201407-chiaki.yotsuya

sudo git clone https://github.com/internousdevjava/201408-fumihiro.okajima
sudo git clone https://github.com/internousdevjava/201408-kazuyuki.sogo

sudo git clone https://github.com/internousdevjava/201409-shota.ebata
sudo git clone https://github.com/internousdevjava/201409-kentaro.isobe
sudo git clone https://github.com/internousdevjava/201409-takato.suzuki
sudo git clone https://github.com/internousdevjava/201409-shingo.sakai
sudo git clone https://github.com/internousdevjava/201409-masateru.honma
sudo git clone https://github.com/internousdevjava/201409-takayuki.wakamatsu
sudo git clone https://github.com/internousdevjava/201409-junpei.yokoyama

sudo git clone https://github.com/internousdevjava/201410-yuki.watanabe
sudo git clone https://github.com/internousdevjava/201410-kensuke.mitsuda
sudo git clone https://github.com/internousdevjava/201410-kyohei.takeuchi
sudo git clone https://github.com/internousdevjava/201410-taishi.kitahara
sudo git clone https://github.com/internousdevjava/201410-takaya.yamanobe

sudo git clone https://github.com/internousdevjava/201411-takahiro.yamaki
sudo git clone https://github.com/internousdevjava/201411-yukiko.sato
sudo git clone https://github.com/internousdevjava/201411-you.kuriya
sudo git clone https://github.com/internousdevjava/201411-hiromasa.ikeda
sudo git clone https://github.com/internousdevjava/201411-marie.hosoya
sudo git clone https://github.com/internousdevjava/201411-aiko.wada

sudo git clone https://github.com/internousdevjava/201412-shinsuke.nakashima
sudo git clone https://github.com/internousdevjava/201412-yusuke.kuga
sudo git clone https://github.com/internousdevjava/201412-ayumi.yamashita
sudo git clone https://github.com/internousdevjava/201412-kinichi.hirayama
sudo git clone https://github.com/internousdevjava/201412-ryoken.isa
sudo git clone https://github.com/internousdevjava/201412-hiroyuki.ozaki
sudo git clone https://github.com/internousdevjava/201412-ishi.dai

sudo git clone https://github.com/internousdevjava/201501-hiroki.kumagai
sudo git clone https://github.com/internousdevjava/201501-miki.haneda
sudo git clone https://github.com/internousdevjava/201501-kazuki.kitayama
sudo git clone https://github.com/internousdevjava/201501-ayako.ootsuka
sudo git clone https://github.com/internousdevjava/201501-takashi.fukuda
sudo git clone https://github.com/internousdevjava/201501-hiroki.nagatsuma
sudo git clone https://github.com/internousdevjava/201501-kumi.hironaga
sudo git clone https://github.com/internousdevjava/201501-azumi.suzuki
sudo git clone https://github.com/internousdevjava/201501-yoko.irei
sudo git clone https://github.com/internousdevjava/201501-kana.oomori
sudo git clone https://github.com/internousdevjava/201501-kana.omori
sudo git clone https://github.com/internousdevjava/201501-tadashi.kurino
sudo git clone https://github.com/internousdevjava/201501-kyohei.shindo
sudo git clone https://github.com/internousdevjava/201501-mana.oyama
sudo git clone https://github.com/internousdevjava/201501-yuki.aoki
sudo git clone https://github.com/internousdevjava/201501-kenta.mikami

sudo git clone https://github.com/internousdevjava/201502-shintaro.iwai
sudo git clone https://github.com/internousdevjava/201502-nakiko.takahashi
sudo git clone https://github.com/internousdevjava/201502-yoshitaka.onoda
sudo git clone https://github.com/internousdevjava/201502-yuta.matsumoto
sudo git clone https://github.com/internousdevjava/201502-ibuki.ikegami
sudo git clone https://github.com/internousdevjava/201502-kento.marushima
sudo git clone https://github.com/internousdevjava/201502-yuya.sato
sudo git clone https://github.com/internousdevjava/201502-kunihiro.handa
sudo git clone https://github.com/internousdevjava/201502-shuhei.uchiumi
sudo git clone https://github.com/internousdevjava/201502-miki.hayashi

sudo git clone https://github.com/internousdevjava/201503-keigo.mori
sudo git clone https://github.com/internousdevjava/201503-kenta.nishikigawa
sudo git clone https://github.com/internousdevjava/201503-shinya.takiyoshi
sudo git clone https://github.com/internousdevjava/201503-takuma.senna
sudo git clone https://github.com/internousdevjava/201503-seiya.miyazaki
sudo git clone https://github.com/internousdevjava/201503-takayoshi.okamoto
sudo git clone https://github.com/internousdevjava/201503-tomoyuki.matsuda
sudo git clone https://github.com/internousdevjava/201503-yoshifumi.narita
sudo git clone https://github.com/internousdevjava/201503-yohei.yamazaki
sudo git clone https://github.com/internousdevjava/201503-tatsuya.mori
sudo git clone https://github.com/internousdevjava/201503-kaito.mizuno
sudo git clone https://github.com/internousdevjava/201503-yuzuru.takahashi
sudo git clone https://github.com/internousdevjava/201503-yuma.goda
sudo git clone https://github.com/internousdevjava/201503-yusuke.matsukawa
sudo git clone https://github.com/internousdevjava/201503-takashi.iwase
sudo git clone https://github.com/internousdevjava/201503-ayumi.katano

sudo git clone https://github.com/internousdevjava/201504-atsushi.tanaka
sudo git clone https://github.com/internousdevjava/201504-akira.funakoshi
sudo git clone https://github.com/internousdevjava/201504-haruka.oosumi
sudo git clone https://github.com/internousdevjava/201504-yuko.nogami
sudo git clone https://github.com/internousdevjava/201504-yoshiaki.kubota
sudo git clone https://github.com/internousdevjava/201504-yoshio.okabe
sudo git clone https://github.com/internousdevjava/201504-yuk.kobori
sudo git clone https://github.com/internousdevjava/201504-koutaro.mito
sudo git clone https://github.com/internousdevjava/201504-akira.miyazono
sudo git clone https://github.com/internousdevjava/201504-hiroshi.niiyama
sudo git clone https://github.com/internousdevjava/201504-reo.okumura
sudo git clone https://github.com/internousdevjava/201504-vite.mark.larr
sudo git clone https://github.com/internousdevjava/201504-junpei.saito
sudo git clone https://github.com/internousdevjava/201504-yuki.kametani

sudo git clone https://github.com/internousdevjava/201505-dai.sugimoto
sudo git clone https://github.com/internousdevjava/201505-tatsuya.tateishi
sudo git clone https://github.com/internousdevjava/201505-satoru.kikuchi
sudo git clone https://github.com/internousdevjava/201505-sno.che
sudo git clone https://github.com/internousdevjava/201505-shouki.tahara
sudo git clone https://github.com/internousdevjava/201505-yuya.hirose
sudo git clone https://github.com/internousdevjava/201505-miyu.koganemaru
sudo git clone https://github.com/internousdevjava/201505-fumiya.murakami
sudo git clone https://github.com/internousdevjava/201505-erika.suzuki
sudo git clone https://github.com/internousdevjava/201505-masakazu.nakamura
sudo git clone https://github.com/internousdevjava/201505-kouta.suzuki
sudo git clone https://github.com/internousdevjava/201505-takuya.noguchi
sudo git clone https://github.com/internousdevjava/201505-kazuyuki.yamada
sudo git clone https://github.com/internousdevjava/201505-yuta.ooki
sudo git clone https://github.com/internousdevjava/201505-kohei.akimoto
sudo git clone https://github.com/internousdevjava/201505-keiichi.horie
sudo git clone https://github.com/internousdevjava/201505-ayaka.kobayashi
sudo git clone https://github.com/internousdevjava/201505-akari.togo
sudo git clone https://github.com/internousdevjava/201505-aiki.kanazawa

sudo git clone https://github.com/internousdevjava/201506-kazuya.iinou
sudo git clone https://github.com/internousdevjava/201506-kokuryo.shu
sudo git clone https://github.com/internousdevjava/201506-hitoshi.kobayashi
sudo git clone https://github.com/internousdevjava/201506-natsumi.iino
sudo git clone https://github.com/internousdevjava/201506-asuka.kobayashi
sudo git clone https://github.com/internousdevjava/201506-tatsushi.okamoto
sudo git clone https://github.com/internousdevjava/201506-hajime.harada
sudo git clone https://github.com/internousdevjava/201506-takeshi.mochizuki
sudo git clone https://github.com/internousdevjava/201506-kensuke.maruyama
sudo git clone https://github.com/internousdevjava/201506-takahiro.nei
sudo git clone https://github.com/internousdevjava/201506-kohei.ishibashi
sudo git clone https://github.com/internousdevjava/201506-ayumu.ueda
sudo git clone https://github.com/internousdevjava/201506-kazushi.sashima
sudo git clone https://github.com/internousdevjava/201506-chiho.akamine
sudo git clone https://github.com/internousdevjava/201506-rina.oshima
sudo git clone https://github.com/internousdevjava/201506-koji.musashi
sudo git clone https://github.com/internousdevjava/201506-kazuki.nishikiori

sudo git clone https://github.com/internousdevjava/201507-daisuke.tago
sudo git clone https://github.com/internousdevjava/201507-shu.yamashita
sudo git clone https://github.com/internousdevjava/201507-shohei.ishikawa
sudo git clone https://github.com/internousdevjava/201507-kohei.seshimo
sudo git clone https://github.com/internousdevjava/201507-masahiro.hagita
sudo git clone https://github.com/internousdevjava/201507-tomohiro.mizutani
sudo git clone https://github.com/internousdevjava/201507-kanako.morikawa
sudo git clone https://github.com/internousdevjava/201507-hikaru.yanagida
sudo git clone https://github.com/internousdevjava/201507-hikaru.mizuguchi
sudo git clone https://github.com/internousdevjava/201507-daisuke.hatamoto
sudo git clone https://github.com/internousdevjava/201507-takahiro.kizawa

sudo git clone https://github.com/internousdevjava/201508-ryutaro.ogata
sudo git clone https://github.com/internousdevjava/201508-masumi.morita
sudo git clone https://github.com/internousdevjava/201508-shigeru.nagata
sudo git clone https://github.com/internousdevjava/201508-toru.tanizawa
sudo git clone https://github.com/internousdevjava/201508-kyohei.ishida
sudo git clone https://github.com/internousdevjava/201508-sayumi.yamasaki
sudo git clone https://github.com/internousdevjava/201508-chihiro.goda
sudo git clone https://github.com/internousdevjava/201508-ryoichi.okamoto

sudo git clone https://github.com/internousdevjava/201509-naomichi.miyashita
sudo git clone https://github.com/internousdevjava/201509-shota.kondo
sudo git clone https://github.com/internousdevjava/201509-ryo.shimada
sudo git clone https://github.com/internousdevjava/201509-ryota.mitsuhashi
sudo git clone https://github.com/internousdevjava/201509-takafumi.fukuoka
sudo git clone https://github.com/internousdevjava/201509-yuki.ikegaya
sudo git clone https://github.com/internousdevjava/201509-takayuki.nohara
sudo git clone https://github.com/internousdevjava/201509-raimu.hara
sudo git clone https://github.com/internousdevjava/201509-ippei.matsushima
sudo git clone https://github.com/internousdevjava/201509-ayane.hoshi
sudo git clone https://github.com/internousdevjava/201509-wataru.kumaki
sudo git clone https://github.com/internousdevjava/201509-tou.chin
sudo git clone https://github.com/internousdevjava/201509-asuka.nagahama
sudo git clone https://github.com/internousdevjava/201509-shotaro.tomo

sudo git clone https://github.com/internousdevjava/201510-michio.tamaki
sudo git clone https://github.com/internousdevjava/201510-keisuke.sagawa
sudo git clone https://github.com/internousdevjava/201510-takuma.inoue
sudo git clone https://github.com/internousdevjava/201510-naho.kitayama
sudo git clone https://github.com/internousdevjava/201510-takayuki.yoshikawa
sudo git clone https://github.com/internousdevjava/201510-kazuki.tahara
sudo git clone https://github.com/internousdevjava/201510-naohiro.minami
sudo git clone https://github.com/internousdevjava/201510-hiroshi.ohama
sudo git clone https://github.com/internousdevjava/201510-youhei.tange
sudo git clone https://github.com/internousdevjava/201510-tatsuki.ozawa
sudo git clone https://github.com/internousdevjava/201510-kana.hosotani
sudo git clone https://github.com/internousdevjava/201510-issei.katata
sudo git clone https://github.com/internousdevjava/201510-shizuka.mizukoshi
sudo git clone https://github.com/internousdevjava/201510-masahiro.namatame
sudo git clone https://github.com/internousdevjava/201510-yuta.kawahigashi
sudo git clone https://github.com/internousdevjava/201510-raiki.kawada
sudo git clone https://github.com/internousdevjava/201510-katsuyuki.kato
sudo git clone https://github.com/internousdevjava/201510-shuntaro.tomiuchi
sudo git clone https://github.com/internousdevjava/201510-hiroaki.hashimoto
sudo git clone https://github.com/internousdevjava/201510-takaharu.sakamoto
sudo git clone https://github.com/internousdevjava/201510-toshikazu.nakata
sudo git clone https://github.com/internousdevjava/201510-akifumi.masui
sudo git clone https://github.com/internousdevjava/201510-masa.tsugawa

sudo git clone https://github.com/internousdevjava/201511-miyuki.harada
sudo git clone https://github.com/internousdevjava/201511-takanobu.kouno
sudo git clone https://github.com/internousdevjava/201511-kenji.suzuya
sudo git clone https://github.com/internousdevjava/201511-miho.kato
sudo git clone https://github.com/internousdevjava/201511-tengo.fukui
sudo git clone https://github.com/internousdevjava/201511-takahiro.watanabe
sudo git clone https://github.com/internousdevjava/201511-kazuhito.matsuda
sudo git clone https://github.com/internousdevjava/201511-masahiro.uchiyama
sudo git clone https://github.com/internousdevjava/201511-Taiga.Kasamatsu
sudo git clone https://github.com/internousdevjava/201511-masaya.taki
sudo git clone https://github.com/internousdevjava/201511-motoki.fukuda
sudo git clone https://github.com/internousdevjava/201511-masaya.sakaguchi

sudo git clone https://github.com/internousdevjava/201512-ryouhei.umezawa
sudo git clone https://github.com/internousdevjava/201512-hisako.horie
sudo git clone https://github.com/internousdevjava/201512-yoichi.takeuchi
sudo git clone https://github.com/internousdevjava/201512-yuta.murakami
sudo git clone https://github.com/internousdevjava/201512-kimino-sugano
sudo git clone https://github.com/internousdevjava/201512-mizuki.kubota
sudo git clone https://github.com/internousdevjava/201512-yuki.tashiro
sudo git clone https://github.com/internousdevjava/201512-koudai.abe
sudo git clone https://github.com/internousdevjava/201512-kazuki.kamijo
sudo git clone https://github.com/internousdevjava/201512-syouma.iiduka
sudo git clone https://github.com/internousdevjava/201512-shou.kobata
sudo git clone https://github.com/internousdevjava/201512-shin.sugimoto
sudo git clone https://github.com/internousdevjava/201512-kouta.hagiwara

sudo git clone https://github.com/internousdevjava/201601-Ryouske.Masaki
sudo git clone https://github.com/internousdevjava/201601-keitarou.kubo
sudo git clone https://github.com/internousdevjava/201601-haruki.nakagawa
sudo git clone https://github.com/internousdevjava/201601-saori.maekawa
sudo git clone https://github.com/internousdevjava/201601-Masateru.Iwata
sudo git clone https://github.com/internousdevjava/201601-yuki.hoshino
sudo git clone https://github.com/internousdevjava/201601-kazutoshi.tsuruta
sudo git clone https://github.com/internousdevjava/201601-kazunori.kudo
sudo git clone https://github.com/internousdevjava/201601-tamaki.fukui
sudo git clone https://github.com/internousdevjava/201601-kazuhiro.yoshihara
sudo git clone https://github.com/internousdevjava/201601-katusaka.kotaki
sudo git clone https://github.com/internousdevjava/201601-wataru.kume
sudo git clone https://github.com/internousdevjava/201601-yurina.sato
sudo git clone https://github.com/internousdevjava/201601-tatsuro.yamazaki
sudo git clone https://github.com/internousdevjava/201601-shizuka.imanishi
sudo git clone https://github.com/internousdevjava/201601-sodai.arakawa
sudo git clone https://github.com/internousdevjava/201601-motonori.tateshita
sudo git clone https://github.com/internousdevjava/201601-yoshiaki.sakai
sudo git clone https://github.com/internousdevjava/201601-takeshi.banshow

sudo git clone https://github.com/internousdevjava/201602-hirobumi.kashiwagi
sudo git clone https://github.com/internousdevjava/201602-takaya.sakuma
sudo git clone https://github.com/internousdevjava/201602-satoru.kanazawa
sudo git clone https://github.com/internousdevjava/201602-tetsuo.asato
sudo git clone https://github.com/internousdevjava/201602-kazutaka.yoshihara
sudo git clone https://github.com/internousdevjava/201602-yuki.kon
sudo git clone https://github.com/internousdevjava/201602-shougo.tooi
sudo git clone https://github.com/internousdevjava/201602-takuma.nitta
sudo git clone https://github.com/internousdevjava/201602-hirotaka.ito
sudo git clone https://github.com/internousdevjava/201602-akira.ota
sudo git clone https://github.com/internousdevjava/201602-yousuke.izumi
sudo git clone https://github.com/internousdevjava/201602-shota.kato
sudo git clone https://github.com/internousdevjava/201602-ryunosuke.matsura
sudo git clone https://github.com/internousdevjava/201602-ki.kon

chmod +x ./*
sudo chown inouetakuma ./*